version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18 # ใช้เวอร์ชัน Node.js ที่ใหม่กว่า
    working_directory: ~/repo
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout

      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # Install Python and AWS CLI
      - run:
          name: Install Python and AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            sudo pip3 install awscli --upgrade

      # Check AWS CLI version
      - run:
          name: Verify AWS CLI installation
          command: aws --version

      # List S3 buckets
      - run:
          name: List S3 buckets
          command: aws s3 ls

      # Deploy application
      - run:
          name: Deploy application
          command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
