version: 2.1  

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies and cache
          command: |
            npm install
            mkdir -p ~/.cache
            cp -r node_modules ~/.cache

      - save_cache:
          paths:
            - ~/.cache/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install Python and AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
     #       sudo pip3 install awscli --upgrade

      # - run:
      #     name: Verify AWS CLI installation
      #     command: aws --version

      # - run:
      #     name: List S3 buckets
      #     command: aws s3 ls

      - run:
          name: Deploy application
          command: npm run deploy

workflows:
  version: 2
  build:
    jobs:
      - build
